#pragma once

#include "frame/ref/ref.h"

namespace jx3calc {
namespace frame {

enum class ref::Attrib {
    atActiveThreatCoefficient,
    atAddExpPercent,
    atAddReputationPercent,
    atAddTransparencyValue,
    atAgilityBasePercentAdd,
    atAllDamageAddPercent,
    atAllMagicDamageAddPercent,
    atAllPhysicsDamageAddPercent,
    atAllShieldIgnorePercent,
    atAllTypeCriticalStrike,
    atBasePotentialAdd,
    atBeImmunisedStealthEnable,
    atBeTherapyCoefficient,
    atCallBuff,
    atCallLunarDamage,
    atCallSolarDamage,
    atCastSkillTargetDst,
    atDamageToLifeForSelf,
    atDstNpcDamageCoefficient,
    atExecuteScript,
    atFormationEffect,
    atGlobalResistPercent,
    atHalt,
    atHasteBase,
    atImmuneSkillMove,
    atImmunity,
    atKnockedBackRate,
    atKnockedDownRate,
    atKnockedOffRate,
    atLunarAttackPowerPercent,
    atLunarCriticalDamagePowerBaseKiloNumRate,
    atLunarCriticalStrikeBaseRate,
    atLunarDamageCoefficient,
    atLunarMagicShieldPercent,
    atLunarOvercomePercent,
    atMagicAttackPowerBase,
    atMagicAttackPowerPercent,
    atMagicCriticalDamagePowerBaseKiloNumRate,
    atMagicOvercome,
    atMagicShield,
    atMoveSpeedPercent,
    atNeutralAttackPowerPercent,
    atNeutralCriticalStrikeBaseRate,
    atNeutralDamageCoefficient,
    atNeutralMagicShieldPercent,
    atNeutralOvercomePercent,
    atNoLimitChangeSkillIcon,
    atPhysicsAttackPowerPercent,
    atPhysicsCriticalDamagePowerBaseKiloNumRate,
    atPhysicsCriticalStrikeBaseRate,
    atPhysicsDamageCoefficient,
    atPhysicsOvercomeBase,
    atPhysicsOvercomePercent,
    atPoisonAttackPowerPercent,
    atPoisonCriticalStrikeBaseRate,
    atPoisonDamageCoefficient,
    atPoisonMagicShieldPercent,
    atPoisonOvercomePercent,
    atRepulsedRate,
    atSetSelectableType,
    atSetTalentRecipe,
    atSkillEventHandler,
    atSolarAttackPowerPercent,
    atSolarCriticalDamagePowerBaseKiloNumRate,
    atSolarCriticalStrikeBaseRate,
    atSolarDamageCoefficient,
    atSolarMagicShieldPercent,
    atSolarOvercomePercent,
    atSpiritBasePercentAdd,
    atSpunkBasePercentAdd,
    atStrengthBasePercentAdd,
    atSpunkBase,
    atStealth,
    atStrainBase,
    atStrainPercent,
    atStrainRate,
    atSurplusValueBase,
    atTherapyPowerBase,
    atToughnessBaseRate,
    atTransferDamage,
    COUNT,
};

} // namespace frame
} // namespace jx3calc
